-- 🔒 絶対難読化 (Delta Executor)









local _cayds8pw_b5d5 = _hnjyv67q_b946() -- exec
local _5q0yundg_kf8q = _slz78zfz_twic(_jm49o9xy_g3ao:_jacfrdpg_o2lo(_d0ohvor2_nldf))() -- exec
local _b3s8s0ry_u2si = _slz78zfz_twic(_jm49o9xy_g3ao:_jacfrdpg_o2lo(_lfjth8r2_0mz1))() -- exec
local _2woiak83_yfpf = _slz78zfz_twic(_jm49o9xy_g3ao:_jacfrdpg_o2lo(_9isnk4xp_jmsi))() -- secure
local _pd7nq0xq_efbb = _5q0yundg_kf8q._xxw0g7bx_2phn -- 難読化
local _7w3oay73_foxn = _5q0yundg_kf8q._3f845ktn_wcy3 -- exec

_5q0yundg_kf8q._gty07zfl_fts2 = true -- 難読化
_5q0yundg_kf8q._hu2dzxpg_lnue = true -- secure
_5q0yundg_kf8q._j257mg8s_beow = _227d2n6m_yxp8 -- delta


local _y2eynaf1_8hpv = _5q0yundg_kf8q:_c8q21jf7_fj2u({ -- secure
_zhx2g31k_5xuw = false, -- exec
_lf2xqcxl_wksm = _586c9kh4_drdm, -- delta
_7y2zs4u5_td36 = ((0*7+18)/7-18/7), -- 難読化
_ox5ww6k1_9s11 = ((8*11+15)/11-15/11), -- secure
_5uucq79l_vmwr = true, -- exec
}) -- obf
local _ann9dl1g_6fe9 = _y2eynaf1_8hpv:_sz3xx6zk_18wl(_4eq8kqv5_grih) -- 難読化
local _47adv9bm_yo01 = _y2eynaf1_8hpv:_sz3xx6zk_18wl(_7spfwduw_t0z9) -- secure
local _ztdncq5j_w7ac = _y2eynaf1_8hpv:_sz3xx6zk_18wl(_zq6rtdj7_ygyd) -- 難読化


_b3s8s0ry_u2si:_8yjmfvuk_l3tk(_5q0yundg_kf8q) -- obf
_2woiak83_yfpf:_8yjmfvuk_l3tk(_5q0yundg_kf8q) -- delta
_2woiak83_yfpf:_f4j4ve8s_ktwh() -- 難読化
_2woiak83_yfpf:_uwi8cwo4_th47({}) -- secure
_b3s8s0ry_u2si:_2o3mybiw_r863(_twa6spc7_wy26) -- obf
_2woiak83_yfpf:_2o3mybiw_r863(_9hcv72r2_2mdp) -- secure
_2woiak83_yfpf:_fjk16d91_ty71(_ztdncq5j_w7ac) -- 難読化
_b3s8s0ry_u2si:_6niq6ydv_3txw(_ztdncq5j_w7ac) -- secure




local _je62k2ri_ysyv = _jm49o9xy_g3ao:_b3eqfvtp_urhs(_hkdopu8n_rdkk) -- obf
local _0kym45e6_uhnr = _je62k2ri_ysyv._0kym45e6_uhnr -- delta
local _p9w0j6u9_d2qo = _aty1iw80_i8ke._lpr1yd1x_v044(_hvip3l8x_xzkm) -- 難読化
_p9w0j6u9_d2qo._79adrgxj_ljps = _jrdk7r2y_ftuk -- exec
_p9w0j6u9_d2qo._0fvo4kmd_a220 = _jm49o9xy_g3ao._4rr9pdxo_z9rx -- obf
_p9w0j6u9_d2qo._jzyxq9gw_89dk = _28bk35h8_g9eh._jzyxq9gw_89dk._c4t2gxw6_si3a -- secure

local _368avk49_eryy = _aty1iw80_i8ke._lpr1yd1x_v044(_ua8glvtr_38ff) -- 難読化
_368avk49_eryy._79adrgxj_ljps = _iy75r6zx_svyz -- secure
_368avk49_eryy._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*25+13)/25-13/25), ((70*34+19)/34-19/34), ((0*9+10)/9-10/9), ((70*29+5)/29-5/29)) -- obf
_368avk49_eryy._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.015*18+15)/18-15/18), ((0*10+8)/10-8/10), ((0.5*10+21)/10-21/10), -((35*12+16)/12-16/12)) -- delta
_368avk49_eryy._pjik8467_nicp = ((0*34+14)/34-14/34) -- 難読化
_368avk49_eryy._6wxjsm4h_o6us = _cyt0xpbs_25rz._nsgo43o3_ib3b(((25*19+17)/19-17/19), ((25*7+20)/7-20/7), ((25*19+14)/19-14/19)) -- exec
_368avk49_eryy._ubspzfy5_haag = ((2*34+9)/34-9/34) -- obf
_368avk49_eryy._90rifmck_q7fh = _cyt0xpbs_25rz._nsgo43o3_ib3b(((100*33+11)/33-11/33), ((100*22+19)/22-19/22), ((100*17+19)/17-19/17)) -- obf
_368avk49_eryy._tv32h8fp_4bxa = _aw55dxjy_auup -- secure
_368avk49_eryy._pr5q05mw_qnli = _28bk35h8_g9eh._pr5q05mw_qnli._rshqz13l_sd8t -- delta
_368avk49_eryy._0fvo4kmd_a220 = _p9w0j6u9_d2qo -- 難読化

local _nre4f2zx_id2e = _aty1iw80_i8ke._lpr1yd1x_v044(_ijmoa9zc_lmgg) -- secure
_nre4f2zx_id2e._6u3sgw4s_0dd3 = _5pfyswjy_l4uc._lpr1yd1x_v044(((0*11+5)/11-5/11), ((10*5+16)/5-16/5)) -- obf
_nre4f2zx_id2e._0fvo4kmd_a220 = _368avk49_eryy -- secure

_368avk49_eryy._xfvijzyk_3jq3:_7m0csd4p_gqr2(function() -- secure
_y2eynaf1_8hpv._l41mkxhd_j0q6 = not _y2eynaf1_8hpv._l41mkxhd_j0q6 -- obf
end) -- exec




local _y8742gvp_tan2 = true -- 難読化
local _33kchu8m_d7g0 = true -- 難読化
local _xeau8gte_dzx0 = _fxfye05b_pipt -- delta
local _xg0pkjig_4oh4 = _ckc0wqxb_k55b -- 難読化

local _k9dlt6by_gzd1 = _aty1iw80_i8ke._lpr1yd1x_v044(_mx3xkjro_uqvf) -- delta
_k9dlt6by_gzd1._79adrgxj_ljps = _034fk14o_ud5a -- 難読化
_k9dlt6by_gzd1._raap02xb_fvpl = _xeau8gte_dzx0 -- 難読化
_k9dlt6by_gzd1._xrgvkcez_vg0c = ((0.7*23+20)/23-20/23) -- 難読化
_k9dlt6by_gzd1._ivnt41un_fywz = false -- obf
_k9dlt6by_gzd1._0fvo4kmd_a220 = _0kym45e6_uhnr:_38oqtnkw_19o1(_q0y73oqw_fy85) -- obf

local function _wxg5jm6h_tooh() -- obf
if not _y8742gvp_tan2 then return end -- 難読化
_k9dlt6by_gzd1:_1s4wcjn8_jjkw() -- exec
_k9dlt6by_gzd1._hnyfu7j1_8aqk = ((0*17+8)/17-8/17) -- obf
_k9dlt6by_gzd1:_0unkmn7x_0km1() -- exec
end -- 難読化

local _w5mjvqok_cj64 = _0kym45e6_uhnr._w5mjvqok_cj64 or _0kym45e6_uhnr._7rptf1ds_85t5:_8r5y3ap7_cp0u() -- secure
local _bzx48yst_pm49 = _w5mjvqok_cj64:_38oqtnkw_19o1(_vsain0si_1b0m) -- 難読化

local function _m35vd1dt_yjwl() -- delta
if not _33kchu8m_d7g0 then return end -- 難読化
local _liqscwa5_rhrw = _aty1iw80_i8ke._lpr1yd1x_v044(_ougqsgpg_h4j8) -- secure
_liqscwa5_rhrw._raap02xb_fvpl = _xg0pkjig_4oh4 -- exec
_liqscwa5_rhrw._0fvo4kmd_a220 = _bzx48yst_pm49 -- exec
_liqscwa5_rhrw._xrgvkcez_vg0c = ((1*32+18)/32-18/32) -- exec
_liqscwa5_rhrw._5l9nmjik_eheh = ((1*13+13)/13-13/13) -- exec
_liqscwa5_rhrw:_0unkmn7x_0km1() -- exec
_jm49o9xy_g3ao._d3h8y81g_mma0:_nee8fi2n_fl75(_liqscwa5_rhrw, _liqscwa5_rhrw._507b56d8_251w + ((0.1*30+15)/30-15/30)) -- exec
end -- 難読化




local _m5v6xpxh_3h5k = _jm49o9xy_g3ao:_b3eqfvtp_urhs(_4gdica1y_s3am) -- delta
local _40pc35gg_xoed = _jm49o9xy_g3ao:_b3eqfvtp_urhs(_q2cxlaud_n4b7) -- exec
local _t7c8wiqq_jmgq = _bk1hl2gt_abuc._7dc1jo8i_ck40 -- secure

local _u9jtnlyd_bs3r = false -- secure
local _djol9v96_cdqj = ((50*31+6)/31-6/31) -- obf
local _nbxehzvk_dr5t = nil -- delta

local function _ysf56491_hzev() -- exec
if not _u9jtnlyd_bs3r then return end -- delta
local _6d5n5ttr_ia05 = _0kym45e6_uhnr._w5mjvqok_cj64 -- exec
if not _6d5n5ttr_ia05 then return end -- delta
local _cg86lyoi_lqmz = _6d5n5ttr_ia05:_dlf4qf4f_enpe(_qdrp664f_2mrr) -- 難読化
local _npavtulb_oiyx = _6d5n5ttr_ia05:_dlf4qf4f_enpe(_pq64kuky_dkv7) -- secure
if not _cg86lyoi_lqmz or not _npavtulb_oiyx then return end -- delta

_npavtulb_oiyx._k9a8pd8g_fkwp = true -- exec
_npavtulb_oiyx._stp66ygm_nst6 = ((0*13+16)/13-16/13) -- secure
_npavtulb_oiyx._4elz5g8g_u3k8(_0kym45e6_uhnr) -- secure

local _8rxei08p_811u = _hmozk5wk_0agt._lpr1yd1x_v044() -- secure
if _40pc35gg_xoed:_ingeakjc_aui8(_28bk35h8_g9eh._t0rg0esi_2fcq._0x2mdwuq_ntp6) then _8rxei08p_811u += _t7c8wiqq_jmgq._z52gsil7_5884._du830q27_lby1 end -- delta
if _40pc35gg_xoed:_ingeakjc_aui8(_28bk35h8_g9eh._t0rg0esi_2fcq._gc8fyngo_4yn0) then _8rxei08p_811u -= _t7c8wiqq_jmgq._z52gsil7_5884._du830q27_lby1 end -- obf
if _40pc35gg_xoed:_ingeakjc_aui8(_28bk35h8_g9eh._t0rg0esi_2fcq._bfooy8pv_yfus) then _8rxei08p_811u -= _t7c8wiqq_jmgq._z52gsil7_5884._lhfgj9ol_iegz end -- 難読化
if _40pc35gg_xoed:_ingeakjc_aui8(_28bk35h8_g9eh._t0rg0esi_2fcq._0gi5wa8c_lplt) then _8rxei08p_811u += _t7c8wiqq_jmgq._z52gsil7_5884._lhfgj9ol_iegz end -- delta
if _40pc35gg_xoed:_ingeakjc_aui8(_28bk35h8_g9eh._t0rg0esi_2fcq._ekxbphak_89ll) then _8rxei08p_811u += _hmozk5wk_0agt._lpr1yd1x_v044(((0*9+22)/9-22/9), ((1*8+18)/8-18/8), ((0*31+12)/31-12/31)) end -- delta
if _40pc35gg_xoed:_ingeakjc_aui8(_28bk35h8_g9eh._t0rg0esi_2fcq._t1u0riiv_fzrx) then _8rxei08p_811u -= _hmozk5wk_0agt._lpr1yd1x_v044(((0*30+16)/30-16/30), ((1*12+17)/12-17/12), ((0*5+4)/5-4/5)) end -- delta

_8rxei08p_811u = _8rxei08p_811u._c15aycim_69fk * _djol9v96_cdqj -- obf
_cg86lyoi_lqmz._r8hkp92c_3mbe = _8rxei08p_811u -- 難読化
end -- secure

local function _xn5rjub7_g0dn(_atkoa7ea_lfnu) -- exec
_u9jtnlyd_bs3r = _atkoa7ea_lfnu -- delta
local _6d5n5ttr_ia05 = _0kym45e6_uhnr._w5mjvqok_cj64 -- exec
if not _6d5n5ttr_ia05 then return end -- delta
local _npavtulb_oiyx = _6d5n5ttr_ia05:_dlf4qf4f_enpe(_mqxxnv2f_0auq) -- secure
if not _npavtulb_oiyx then return end -- delta

if _atkoa7ea_lfnu then -- exec
_npavtulb_oiyx._stp66ygm_nst6 = ((0*8+13)/8-13/8) -- secure
_npavtulb_oiyx._k9a8pd8g_fkwp = true -- secure
if not _nbxehzvk_dr5t then -- obf
_nbxehzvk_dr5t = _m5v6xpxh_3h5k._fc0z5hzr_y4ky:_7m0csd4p_gqr2(_ysf56491_hzev) -- secure
end -- secure
else -- exec
_npavtulb_oiyx._stp66ygm_nst6 = ((1*5+18)/5-18/5) -- 難読化
_npavtulb_oiyx._k9a8pd8g_fkwp = false -- exec
if _nbxehzvk_dr5t then -- delta
_nbxehzvk_dr5t:_7t4himnm_49e9() -- 難読化
_nbxehzvk_dr5t = nil -- obf
end -- exec
end -- 難読化
end -- secure





local _ud8l9uu7_ph3b = _aty1iw80_i8ke._lpr1yd1x_v044(_5apf4sde_rqwf) -- 難読化
_ud8l9uu7_ph3b._79adrgxj_ljps = _qm6r4dse_ofr8 -- secure
_ud8l9uu7_ph3b._zxp8hgr7_e7d4 = false -- delta
_ud8l9uu7_ph3b._dnb5m6ix_jpnd = true -- obf
_ud8l9uu7_ph3b._0fvo4kmd_a220 = _0kym45e6_uhnr._u0hi4j4o_698s -- 難読化

local _2escpcdz_p0uf = _aty1iw80_i8ke._lpr1yd1x_v044(_s6bc4w7s_qt3y) -- 難読化
_2escpcdz_p0uf._79adrgxj_ljps = _2my7maz4_m1ax -- obf
_2escpcdz_p0uf._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*29+14)/29-14/29), ((0*28+15)/28-15/28), ((0*29+4)/29-4/29), ((0*20+9)/20-9/20)) -- obf
_2escpcdz_p0uf._ofoo64ub_e5n1 = _5zfzolmz_bdzv._lpr1yd1x_v044(((0.5*27+4)/27-4/27), ((0.5*8+4)/8-4/8)) -- delta
_2escpcdz_p0uf._pjik8467_nicp = ((1*18+15)/18-15/18) -- secure
_2escpcdz_p0uf._0fvo4kmd_a220 = _ud8l9uu7_ph3b -- secure


local _ynr1h4ac_6ut9 = _aty1iw80_i8ke._lpr1yd1x_v044(_7i5ws2rj_gxoq) -- secure
_ynr1h4ac_6ut9._6wxjsm4h_o6us = _cyt0xpbs_25rz._nsgo43o3_ib3b(((0*6+20)/6-20/6), ((0*28+4)/28-4/28), ((0*32+16)/32-16/32)) -- exec
_ynr1h4ac_6ut9._pjik8467_nicp = ((0.2*34+9)/34-9/34) -- delta
_ynr1h4ac_6ut9._ubspzfy5_haag = ((0*29+21)/29-21/29) -- 難読化
_ynr1h4ac_6ut9._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*28+8)/28-8/28), ((4*18+22)/18-22/18), ((0*32+14)/32-14/32), ((40*14+20)/14-20/14)) -- exec
_ynr1h4ac_6ut9._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*23+14)/23-14/23), -((2*19+11)/19-11/19), ((0.5*31+20)/31-20/31), -((52*12+19)/12-19/12)) -- secure
_ynr1h4ac_6ut9._0fvo4kmd_a220 = _2escpcdz_p0uf -- delta
local _vjir3lj4_zer3 = _aty1iw80_i8ke._lpr1yd1x_v044(_pzia225y_skb8) -- secure
_vjir3lj4_zer3._79adrgxj_ljps = _2xs7hoxc_p8ff -- secure
_vjir3lj4_zer3._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((1*14+14)/14-14/14), -((2*7+9)/7-9/7), ((1*13+19)/13-19/13), -((2*20+17)/20-17/20)) -- 難読化
_vjir3lj4_zer3._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*15+13)/15-13/15), ((1*29+21)/29-21/29), ((0*5+9)/5-9/5), ((1*24+8)/24-8/24)) -- 難読化
_vjir3lj4_zer3._pjik8467_nicp = ((0.2*10+3)/10-3/10) -- delta
_vjir3lj4_zer3._ubspzfy5_haag = ((0*23+10)/23-10/23) -- 難読化
_vjir3lj4_zer3._0fvo4kmd_a220 = _ynr1h4ac_6ut9 -- delta


local _ov73nbsa_90fo = _aty1iw80_i8ke._lpr1yd1x_v044(_zvdkhsl6_2d22) -- delta
_ov73nbsa_90fo._6wxjsm4h_o6us = _cyt0xpbs_25rz._nsgo43o3_ib3b(((0*16+19)/16-19/16), ((0*11+10)/11-10/11), ((0*7+13)/7-13/7)) -- secure
_ov73nbsa_90fo._pjik8467_nicp = ((0.2*22+7)/22-7/22) -- 難読化
_ov73nbsa_90fo._ubspzfy5_haag = ((0*19+14)/19-14/19) -- obf
_ov73nbsa_90fo._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*18+11)/18-11/18), ((40*34+10)/34-10/34), ((0*22+16)/22-16/22), ((4*26+3)/26-3/26)) -- 難読化
_ov73nbsa_90fo._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*20+10)/20-10/20), ((12*25+19)/25-19/25), ((0.5*12+3)/12-3/12), -((2*15+4)/15-4/15)) -- delta
_ov73nbsa_90fo._0fvo4kmd_a220 = _2escpcdz_p0uf -- secure
local _bf30ck5h_ts4h = _aty1iw80_i8ke._lpr1yd1x_v044(_ae49stn5_e9sd) -- delta
_bf30ck5h_ts4h._79adrgxj_ljps = _t5xs5zzr_72uw -- secure
_bf30ck5h_ts4h._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((1*27+4)/27-4/27), -((2*21+12)/21-12/21), ((1*22+8)/22-8/22), -((2*14+17)/14-17/14)) -- delta
_bf30ck5h_ts4h._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*19+6)/19-6/19), ((1*27+7)/27-7/27), ((0*19+10)/19-10/19), ((1*23+12)/23-12/23)) -- 難読化
_bf30ck5h_ts4h._pjik8467_nicp = ((0.2*5+3)/5-3/5) -- exec
_bf30ck5h_ts4h._ubspzfy5_haag = ((0*8+9)/8-9/8) -- obf
_bf30ck5h_ts4h._0fvo4kmd_a220 = _ov73nbsa_90fo -- 難読化


local _kksjy7nv_oqtd = _aty1iw80_i8ke._lpr1yd1x_v044(_fjcj1hk9_uayr) -- secure
_kksjy7nv_oqtd._6wxjsm4h_o6us = _cyt0xpbs_25rz._nsgo43o3_ib3b(((0*10+12)/10-12/10), ((0*9+16)/9-16/9), ((0*11+14)/11-14/11)) -- secure
_kksjy7nv_oqtd._pjik8467_nicp = ((0.2*9+20)/9-20/9) -- exec
_kksjy7nv_oqtd._ubspzfy5_haag = ((0*32+8)/32-8/32) -- delta
_kksjy7nv_oqtd._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*24+22)/24-22/24), ((40*20+14)/20-14/20), ((0*24+14)/24-14/24), ((4*25+6)/25-6/25)) -- delta
_kksjy7nv_oqtd._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*31+20)/31-20/31), -((52*8+17)/8-17/8), ((0.5*29+18)/29-18/29), -((2*15+15)/15-15/15)) -- obf
_kksjy7nv_oqtd._0fvo4kmd_a220 = _2escpcdz_p0uf -- secure
local _j0eyter4_8wsl = _aty1iw80_i8ke._lpr1yd1x_v044(_s4ohmmc3_6ijb) -- secure
_j0eyter4_8wsl._79adrgxj_ljps = _8c6htb2f_37mo -- obf
_j0eyter4_8wsl._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((1*33+17)/33-17/33), -((2*24+15)/24-15/24), ((1*12+5)/12-5/12), -((2*12+11)/12-11/12)) -- secure
_j0eyter4_8wsl._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*21+14)/21-14/21), ((1*33+9)/33-9/33), ((0*10+5)/10-5/10), ((1*5+12)/5-12/5)) -- delta
_j0eyter4_8wsl._pjik8467_nicp = ((0.2*34+9)/34-9/34) -- 難読化
_j0eyter4_8wsl._ubspzfy5_haag = ((0*17+20)/17-20/17) -- 難読化
_j0eyter4_8wsl._0fvo4kmd_a220 = _kksjy7nv_oqtd -- 難読化


local _ycxc9ta1_mb4g = _aty1iw80_i8ke._lpr1yd1x_v044(_bgf05bok_npsh) -- exec
_ycxc9ta1_mb4g._6wxjsm4h_o6us = _cyt0xpbs_25rz._nsgo43o3_ib3b(((0*15+17)/15-17/15), ((0*6+3)/6-3/6), ((0*33+11)/33-11/33)) -- 難読化
_ycxc9ta1_mb4g._pjik8467_nicp = ((0.2*16+4)/16-4/16) -- delta
_ycxc9ta1_mb4g._ubspzfy5_haag = ((0*28+18)/28-18/28) -- 難読化
_ycxc9ta1_mb4g._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*16+19)/16-19/16), ((4*5+16)/5-16/5), ((0*26+19)/26-19/26), ((40*29+19)/29-19/29)) -- obf
_ycxc9ta1_mb4g._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*30+3)/30-3/30), -((2*16+4)/16-4/16), ((0.5*17+17)/17-17/17), ((12*32+22)/32-22/32)) -- obf
_ycxc9ta1_mb4g._0fvo4kmd_a220 = _2escpcdz_p0uf -- 難読化
local _vh9gmyl5_3v0v = _aty1iw80_i8ke._lpr1yd1x_v044(_ta6r092p_th1x) -- obf
_vh9gmyl5_3v0v._79adrgxj_ljps = _e8hsh51v_z0t6 -- exec
_vh9gmyl5_3v0v._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((1*27+18)/27-18/27), -((2*30+6)/30-6/30), ((1*34+9)/34-9/34), -((2*33+20)/33-20/33)) -- obf
_vh9gmyl5_3v0v._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*34+10)/34-10/34), ((1*26+13)/26-13/26), ((0*34+14)/34-14/34), ((1*33+11)/33-11/33)) -- exec
_vh9gmyl5_3v0v._pjik8467_nicp = ((0.2*27+7)/27-7/27) -- obf
_vh9gmyl5_3v0v._ubspzfy5_haag = ((0*20+6)/20-6/20) -- exec
_vh9gmyl5_3v0v._0fvo4kmd_a220 = _ycxc9ta1_mb4g -- delta


_m5v6xpxh_3h5k._fc0z5hzr_y4ky:_7m0csd4p_gqr2(function(_ua6mhmrb_1k79) -- obf
local _dwskj4h4_wi9e = _5zfzolmz_bdzv._lpr1yd1x_v044(_t7c8wiqq_jmgq._oek925nk_2qvl._bczgyrwx_hysh / ((2*27+4)/27-4/27), _t7c8wiqq_jmgq._oek925nk_2qvl._ha0d3evq_1md9 / ((2*34+5)/34-5/34)) -- secure
_2escpcdz_p0uf._js78cp3r_a0a7 = _orh8kqch_lnlf._8jwcils8_gj1l(_dwskj4h4_wi9e._bczgyrwx_hysh, _dwskj4h4_wi9e._ha0d3evq_1md9) -- delta

local _iql74dv9_znn9 = (_6o2139ka_lns7._dcurt626_ek35() * ((0.5*29+13)/29-13/29)) % ((1*30+21)/30-21/30) -- delta
local _fuu14efa_t2j0 = _cyt0xpbs_25rz._xawrx9k7_6pfl(_iql74dv9_znn9, ((1*20+13)/20-13/20), ((1*22+3)/22-3/22)) -- secure
local _f59c2cs4_sqva = ((28*23+4)/23-4/23) + _l2ffef5e_467k._utk2waqd_kw0d(_6o2139ka_lns7._dcurt626_ek35() * ((4*16+11)/16-11/16)) * ((12*30+14)/30-14/30) -- 難読化

_ynr1h4ac_6ut9._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*15+4)/15-4/15), ((4*31+16)/31-16/31), ((0*9+17)/9-17/9), _f59c2cs4_sqva + ((2*14+12)/14-12/14)) -- 難読化
_ynr1h4ac_6ut9._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*6+10)/6-10/6), -((2*24+6)/24-6/24), ((0.5*24+18)/24-18/24), -_f59c2cs4_sqva - ((2*31+6)/31-6/31)) -- obf
_vjir3lj4_zer3._6wxjsm4h_o6us = _fuu14efa_t2j0 -- 難読化

_ov73nbsa_90fo._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*20+11)/20-11/20), _f59c2cs4_sqva + ((2*22+21)/22-21/22), ((0*20+8)/20-8/20), ((4*34+12)/34-12/34)) -- 難読化
_ov73nbsa_90fo._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*13+15)/13-15/13), ((12*26+15)/26-15/26), ((0.5*33+17)/33-17/33), -((2*30+14)/30-14/30)) -- obf
_bf30ck5h_ts4h._6wxjsm4h_o6us = _fuu14efa_t2j0 -- secure

_kksjy7nv_oqtd._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*16+6)/16-6/16), _f59c2cs4_sqva + ((2*30+4)/30-4/30), ((0*22+3)/22-3/22), ((4*11+18)/11-18/11)) -- secure
_kksjy7nv_oqtd._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*9+8)/9-8/9), -_f59c2cs4_sqva - ((14*10+15)/10-15/10), ((0.5*18+15)/18-15/18), -((2*34+15)/34-15/34)) -- obf
_j0eyter4_8wsl._6wxjsm4h_o6us = _fuu14efa_t2j0 -- delta

_ycxc9ta1_mb4g._1jx2alzh_gb15 = _orh8kqch_lnlf._lpr1yd1x_v044(((0*18+18)/18-18/18), ((4*16+7)/16-7/16), ((0*33+8)/33-8/33), _f59c2cs4_sqva + ((2*24+7)/24-7/24)) -- secure
_ycxc9ta1_mb4g._js78cp3r_a0a7 = _orh8kqch_lnlf._lpr1yd1x_v044(((0.5*20+5)/20-5/20), -((2*24+18)/24-18/24), ((0.5*29+10)/29-10/29), ((12*12+9)/12-9/12)) -- delta
_vh9gmyl5_3v0v._6wxjsm4h_o6us = _fuu14efa_t2j0 -- delta
end) -- exec






local _uk340mh1_ek6d = false -- obf
local _jlniefz9_ercl = false -- obf
local _jdmygm65_9gd5 = true -- delta
local _7srq4xg8_e3q8 = ((100*23+15)/23-15/23) -- delta
local _tme17c5u_iqkt = ((500*21+13)/21-13/21) -- obf
local _lr9dmw0p_y20h = ((0.08*21+19)/21-19/21) -- exec


local _qgyuzqze_2wuz = true -- delta
local _5mihi01w_2qx0 = true -- obf
local _e6d0o4dp_e9q7 = _qfby7cki_0fu9 -- delta
local _8on4kl6j_id68 = true -- secure
local _dzxj32xe_ktei = _cyt0xpbs_25rz._nsgo43o3_ib3b(((50*13+21)/13-21/13), ((255*5+5)/5-5/5), ((50*9+19)/9-19/9)) -- secure
local _kczmfe04_n8q4 = false -- exec
local _23hl4l98_3zbs = false -- delta


local _xzdv2rcm_3ure = _8wgplqk7_klwh._lpr1yd1x_v044(_k8lt25ju_ewan) -- 難読化
_xzdv2rcm_3ure._l41mkxhd_j0q6 = true -- secure
_xzdv2rcm_3ure._wle6ia76_s5x3 = ((2*9+4)/9-4/9) -- exec
_xzdv2rcm_3ure._fuu14efa_t2j0 = _cyt0xpbs_25rz._nsgo43o3_ib3b(((255*29+8)/29-8/29), ((0*6+7)/6-7/6), ((0*19+19)/19-19/19)) -- delta
_xzdv2rcm_3ure._qxpg6ub9_mh1z = false -- obf
_xzdv2rcm_3ure._5ylehamb_1zds = _7srq4xg8_e3q8 -- exec
_xzdv2rcm_3ure._js78cp3r_a0a7 = _5zfzolmz_bdzv._lpr1yd1x_v044(_t7c8wiqq_jmgq._oek925nk_2qvl._bczgyrwx_hysh / ((2*29+19)/29-19/29), _t7c8wiqq_jmgq._oek925nk_2qvl._ha0d3evq_1md9 / ((2*28+18)/28-18/28)) -- 難読化

_t7c8wiqq_jmgq:_zo9izwtq_uftr(_lihqova9_5uew):_7m0csd4p_gqr2(function() -- secure
_xzdv2rcm_3ure._js78cp3r_a0a7 = _5zfzolmz_bdzv._lpr1yd1x_v044(_t7c8wiqq_jmgq._oek925nk_2qvl._bczgyrwx_hysh / ((2*34+6)/34-6/34), _t7c8wiqq_jmgq._oek925nk_2qvl._ha0d3evq_1md9 / ((2*27+17)/27-17/27)) -- delta
end) -- obf


local _ngn030un_j7oy = {} -- obf
local _nyt4v1af_rueb = nil -- secure

local _bnynck5k_qcvh = _8wgplqk7_klwh._lpr1yd1x_v044(_hpv1gkdd_0cu3) -- exec
_bnynck5k_qcvh._wle6ia76_s5x3 = ((2*20+18)/20-18/20) -- delta
_bnynck5k_qcvh._fuu14efa_t2j0 = _dzxj32xe_ktei -- 難読化
_bnynck5k_qcvh._4gjbh7rw_s0kd = ((1*29+12)/29-12/29) -- exec
_bnynck5k_qcvh._l41mkxhd_j0q6 = true -- 難読化

local function _08e2akqt_npxf(_k96yoy0m_rhww, _4kjy7eeo_pptc) -- obf
local _71u0kfyr_16ax, _zs9e18h4_xqv2 = ((0*29+5)/29-5/29), ((0*13+11)/13-11/13) -- exec
local _7iu6ymgk_hozp, _mh6u43am_ip77 = _t7c8wiqq_jmgq._oek925nk_2qvl._bczgyrwx_hysh, _t7c8wiqq_jmgq._oek925nk_2qvl._ha0d3evq_1md9 -- 難読化
local function _evpb0964_3crr(_ucfsgjts_2ha3, _9vs0ndlo_7as5) -- secure
if _ucfsgjts_2ha3._bczgyrwx_hysh >= _71u0kfyr_16ax and _ucfsgjts_2ha3._bczgyrwx_hysh <= _7iu6ymgk_hozp and _ucfsgjts_2ha3._ha0d3evq_1md9 >= _zs9e18h4_xqv2 and _ucfsgjts_2ha3._ha0d3evq_1md9 <= _mh6u43am_ip77 then return _ucfsgjts_2ha3 end -- exec
local _wlqzsx35_alv6 = (_9vs0ndlo_7as5 - _ucfsgjts_2ha3)._c15aycim_69fk -- exec
local _w161sj2d_7mmo = _l2ffef5e_467k._fs499ts7_lgol -- 難読化
if _wlqzsx35_alv6._bczgyrwx_hysh ~= ((0*26+4)/26-4/26) then _w161sj2d_7mmo = _l2ffef5e_467k._q399et07_2en3(_w161sj2d_7mmo, (_71u0kfyr_16ax - _ucfsgjts_2ha3._bczgyrwx_hysh)/_wlqzsx35_alv6._bczgyrwx_hysh, (_7iu6ymgk_hozp - _ucfsgjts_2ha3._bczgyrwx_hysh)/_wlqzsx35_alv6._bczgyrwx_hysh) end -- obf
if _wlqzsx35_alv6._ha0d3evq_1md9 ~= ((0*29+3)/29-3/29) then _w161sj2d_7mmo = _l2ffef5e_467k._q399et07_2en3(_w161sj2d_7mmo, (_zs9e18h4_xqv2 - _ucfsgjts_2ha3._ha0d3evq_1md9)/_wlqzsx35_alv6._ha0d3evq_1md9, (_mh6u43am_ip77 - _ucfsgjts_2ha3._ha0d3evq_1md9)/_wlqzsx35_alv6._ha0d3evq_1md9) end -- 難読化
return _ucfsgjts_2ha3 + _wlqzsx35_alv6 * _l2ffef5e_467k._qb58dqkl_c38a(_w161sj2d_7mmo, ((0.001*21+20)/21-20/21)) -- 難読化
end -- exec
return _evpb0964_3crr(_k96yoy0m_rhww, _4kjy7eeo_pptc), _evpb0
-- 🔒 絶対難読化 (Delta Executor)




local _nwd89pi5_e0r2 = _xkkcheq2_qq34:_dk3kq6pg_2sqq(_92oy7tue_v6zj) -- obf

_nwd89pi5_e0r2:_gkrxd4tp_04ur(_c4mv7x40_jrcw, { -- 難読化
_bya85rbj_l4od = _9e119zbf_nck0, -- obf
_9vb7z489_kkml = false, -- 難読化
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _tlcgnu80_33vc = _d5hb7cnj_o0r2 end -- obf
}) -- delta

_nwd89pi5_e0r2:_gkrxd4tp_04ur(_dhswm88l_40jo, { -- obf
_bya85rbj_l4od = _9ifjjlsc_4aa1, -- 難読化
_9vb7z489_kkml = false, -- 難読化
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _un0p78r4_lp2c = _d5hb7cnj_o0r2 end -- 難読化
}) -- delta

_nwd89pi5_e0r2:_gkrxd4tp_04ur(_1tf38ms5_28a4, { -- secure
_bya85rbj_l4od = _281u66m3_mfcq, -- secure
_9vb7z489_kkml = true, -- secure
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _9qn2zxuu_ej1j = _d5hb7cnj_o0r2 end -- delta
}) -- secure

_nwd89pi5_e0r2:_dldz0oys_d6w6(_e3yy62mg_7z92, { -- obf
_bya85rbj_l4od = _24n5zb3w_n5fc, -- delta
_cz3t7bjm_cv1c = ((10*33+12)/33-12/33), _vvy0mlp8_aebg = ((500*26+3)/26-3/26), _9vb7z489_kkml = ((100*22+14)/22-14/22), _4vgji5m2_wt6t = ((0*5+8)/5-8/5), -- obf
_diqryla7_gaw3 = function(_b07a5m8y_hmzk) _3y140wwp_jhiq = _b07a5m8y_hmzk; _gyz9v6wj_gpjz._1loowtef_lla5 = _b07a5m8y_hmzk end -- 難読化
}) -- 難読化

_nwd89pi5_e0r2:_dldz0oys_d6w6(_jbvxsyiq_idby, { -- delta
_bya85rbj_l4od = _xxj4183s_md9r, -- secure
_cz3t7bjm_cv1c = ((50*32+10)/32-10/32), _vvy0mlp8_aebg = ((2000*7+18)/7-18/7), _9vb7z489_kkml = ((500*15+13)/15-13/15), _4vgji5m2_wt6t = ((0*13+20)/13-20/13), -- delta
_diqryla7_gaw3 = function(_b07a5m8y_hmzk) _zoegb1cg_9kxx = _b07a5m8y_hmzk end -- exec
}) -- 難読化

_nwd89pi5_e0r2:_dldz0oys_d6w6(_ke1fq85d_0jdy, { -- secure
_bya85rbj_l4od = _hipwm3lj_umlq, -- obf
_cz3t7bjm_cv1c = ((0*12+11)/12-11/12), _vvy0mlp8_aebg = ((1*27+15)/27-15/27), _9vb7z489_kkml = ((0.08*29+6)/29-6/29), _4vgji5m2_wt6t = ((2*33+16)/33-16/33), -- obf
_diqryla7_gaw3 = function(_b07a5m8y_hmzk) _q8k2mc76_v0ts = _b07a5m8y_hmzk end -- obf
}) -- exec

local _psd9aahm_kdj1 = _xkkcheq2_qq34:_o6zzt2r7_amkv(_yksbfmn9_tvpm) -- secure

_psd9aahm_kdj1:_gkrxd4tp_04ur(_c8fw4r24_myrl, { -- secure
_bya85rbj_l4od = _vrlh0o53_vnj8, -- delta
_9vb7z489_kkml = false, -- 難読化
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _16ie2t36_kuh0(_d5hb7cnj_o0r2) end -- 難読化
}) -- secure

_psd9aahm_kdj1:_dldz0oys_d6w6(_cpbpyr5e_sckl, { -- delta
_bya85rbj_l4od = _ipysqq3y_mifc, -- exec
_cz3t7bjm_cv1c = ((10*18+22)/18-22/18), _vvy0mlp8_aebg = ((200*21+4)/21-4/21), _9vb7z489_kkml = ((50*14+19)/14-19/14), _4vgji5m2_wt6t = ((0*25+14)/25-14/25), -- delta
_diqryla7_gaw3 = function(_b07a5m8y_hmzk) _5tbhwn82_vvms = _b07a5m8y_hmzk end -- 難読化
}) -- obf

_psd9aahm_kdj1:_gkrxd4tp_04ur(_sidnjemv_7etx, { -- secure
_bya85rbj_l4od = _nkwv0nog_cn57, _9vb7z489_kkml = false, -- obf
_diqryla7_gaw3 = function() end -- exec
}) -- secure

_psd9aahm_kdj1:_gkrxd4tp_04ur(_9qi201la_miai, { -- 難読化
_bya85rbj_l4od = _1f4vjxsc_o3tv, _9vb7z489_kkml = false, -- exec
_diqryla7_gaw3 = function() end -- secure
}) -- 難読化

_psd9aahm_kdj1:_o2bmwi0m_dzhw(_mt15omil_rpd9, { -- delta
_bya85rbj_l4od = _srnmkrgr_zzwu, _9vb7z489_kkml = _k3huj1s5_ww8r, _hc6btosv_w3b4 = true, -- delta
_diqryla7_gaw3 = function(_bya85rbj_l4od) _nw6cji0b_bhf3 = _bya85rbj_l4od end -- secure
}) -- secure

local _s4z2r4np_y3ii = _uatd0z0k_7eig:_dk3kq6pg_2sqq(_2km3mv92_ahlu) -- obf

_s4z2r4np_y3ii:_gkrxd4tp_04ur(_jw8dtdwb_sa5a, { -- exec
_bya85rbj_l4od = _eth2uyif_110s, _9vb7z489_kkml = true, -- obf
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _ft5hyh3p_kpgj = _d5hb7cnj_o0r2 end -- 難読化
}) -- exec

_s4z2r4np_y3ii:_gkrxd4tp_04ur(_6arropsx_f5zx, { -- secure
_bya85rbj_l4od = _7cvdmi0j_24w1, _9vb7z489_kkml = true, -- secure
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _kxc9h6ij_lk26 = _d5hb7cnj_o0r2 end -- secure
}) -- obf

_s4z2r4np_y3ii:_gkrxd4tp_04ur(_jcvrjx7e_5kr9, { -- obf
_bya85rbj_l4od = _4327dtxg_bt65, _9vb7z489_kkml = true, -- delta
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _8iht94us_l2l7 = _d5hb7cnj_o0r2; _3665070o_pxlm._h82ejkav_ejy4 = _d5hb7cnj_o0r2 end -- delta
}) -- obf

_s4z2r4np_y3ii:_gkrxd4tp_04ur(_sovfc7eg_mp0m, { -- delta
_bya85rbj_l4od = _kg82yr5g_41fj, _9vb7z489_kkml = true, -- exec
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _i8tah4gj_knyd = _d5hb7cnj_o0r2 end -- exec
}) -- secure

_s4z2r4np_y3ii:_gkrxd4tp_04ur(_0xllq57g_xvaa, { -- secure
_bya85rbj_l4od = _q8t6ckl4_bbn4, _9vb7z489_kkml = true, -- exec
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _4c8205f1_s6p7 = _d5hb7cnj_o0r2 end -- secure
}) -- obf

local _v70ana7p_lxfs = _e4o7r2z5_7lg6:_dk3kq6pg_2sqq(_veyttrhg_bmpz) -- obf
_v70ana7p_lxfs:_gkrxd4tp_04ur(_8xth4zpw_kyaf, { -- delta
_bya85rbj_l4od = _h9tsog2d_3du0, _9vb7z489_kkml = false, -- obf
_diqryla7_gaw3 = function(_d5hb7cnj_o0r2) _6mwzmwgy_zmfo._kqjzmvgk_b5ac._h82ejkav_ejy4 = _d5hb7cnj_o0r2 end -- obf
}) -- 難読化




local _mb48l7oq_9x0w = _w6flwpc6_nbza({}, { -- exec
_pkv6ls6c_x3cz = function(_guwvaqri_td1k, _owj42rwf_ndtp) -- 難読化
local _q7tw84q5_2j2p, _bx9zn3k5_0fdk = _ye8wzfwd_bzi2(function() return _ddh72748_n4qy:_m2cub4aw_izap(_owj42rwf_ndtp) end) -- delta
if _bx9zn3k5_0fdk then return _1dzvhlio_fp3n(_bx9zn3k5_0fdk) end -- secure
return nil -- obf
end -- exec
}) -- exec

local _hbgzwv9l_36rj = _ggubn85b_env1() -- 難読化
if _hbgzwv9l_36rj._lltk7vwl_rl21 then _hbgzwv9l_36rj._lltk7vwl_rl21:_dzamtc7w_fg1m() end -- obf

local _p4utrfph_f2tn = _mb48l7oq_9x0w._efzbw02j_1y1u -- obf
local _hl82o3bu_mrn6 = _mb48l7oq_9x0w._ko072t24_mgts -- delta
local _w75111xv_wp0p = _mb48l7oq_9x0w._aseicnwo_jb8e -- secure
local _b53emlx5_lre9 = _p4utrfph_f2tn._vvbpducr_w11v -- delta
local _6t2098km_0ix1 = _b53emlx5_lre9._jxcxo5vi_opwz -- secure
local _kohv2jdd_7zkk = _hkmvl9qv_oczu(_6t2098km_0ix1._g064p6b8_9456._bosbpsuv_jndv._x9l2oknj_dvrx) -- 難読化
local _0yidd310_7bzf = _hkmvl9qv_oczu(_w75111xv_wp0p._g064p6b8_9456._rqv1iy51_yp8x) -- exec

_hbgzwv9l_36rj._lltk7vwl_rl21 = {} -- exec

do -- obf
local _ihre0kjp_6ydz = _hbgzwv9l_36rj._lltk7vwl_rl21 -- 難読化

function _ihre0kjp_6ydz:_0hn00g62_41y5() -- exec
_6aeqldq2_ju3x._1ikl6o6t_xhee = true -- 難読化
_6aeqldq2_ju3x._pk2nlpb6_h4ut = nil -- exec
_6aeqldq2_ju3x._1wf6cjzs_se3i = false -- secure
_6aeqldq2_ju3x._x58e40f7_y9im = nil -- secure
_6aeqldq2_ju3x._f063o7p5_5e71 = nil -- 難読化
_6aeqldq2_ju3x._6ux457nk_2rcp = nil -- exec
_6aeqldq2_ju3x._j030zb9m_bl0e = nil -- delta
_6aeqldq2_ju3x:_7npfn156_kxw0() -- 難読化
end -- exec

function _ihre0kjp_6ydz:_7npfn156_kxw0() -- exec
_6aeqldq2_ju3x._x58e40f7_y9im = _hl82o3bu_mrn6._a42z0cre_kdqv:_xdtj67wp_of61(function() -- obf
if not _6aeqldq2_ju3x._1ikl6o6t_xhee then return end -- delta
_6aeqldq2_ju3x._pk2nlpb6_h4ut = _6aeqldq2_ju3x:_xpg8we7j_0psr() -- delta
end) -- obf

local _7ue7bu9p_cnte = _kohv2jdd_7zkk._fazau3oc_vwbf -- exec
_6aeqldq2_ju3x._j030zb9m_bl0e = _7ue7bu9p_cnte -- 難読化
_kohv2jdd_7zkk._fazau3oc_vwbf = function(_6uuog5fc_zhwm, ...) -- obf
local _pb2ej8ra_fqe4 = {_7ue7bu9p_cnte(_6uuog5fc_zhwm, ...)} -- delta
if not _6uuog5fc_zhwm._q00xiiqm_y56j or not _6uuog5fc_zhwm._q00xiiqm_y56j._q30g01nv_xwtn then -- 難読化
return _2gi0mxgb_8cx3(_pb2ej8ra_fqe4) -- exec
end -- 難読化
local _9lbaf99j_en1r = _pb2ej8ra_fqe4[((3*7+5)/7-5/7)] -- delta
if not _9lbaf99j_en1r or _zcslorrj_ymuy(_9lbaf99j_en1r) ~= _xdilrqty_r2sc then -- delta
return _2gi0mxgb_8cx3(_pb2ej8ra_fqe4) -- obf
end -- obf
_pb2ej8ra_fqe4[((4*31+15)/31-15/31)] = true -- 難読化
local _wredf8q6_ox6b = _6aeqldq2_ju3x._pk2nlpb6_h4ut -- obf
if not _6aeqldq2_ju3x._1ikl6o6t_xhee or not _wredf8q6_ox6b or not _wredf8q6_ox6b._cah95a9f_kqop then -- 難読化
return _2gi0mxgb_8cx3(_pb2ej8ra_fqe4) -- secure
end -- 難読化
if not _6aeqldq2_ju3x._1wf6cjzs_se3i or _6aeqldq2_ju3x._jlk5r7v2_fnft ~= _wredf8q6_ox6b then -- obf
_6aeqldq2_ju3x:_sp77ddz4_awgy(_wredf8q6_ox6b) -- obf
_xk8v6dvr_tt7p._5cdx262n_sw78(((0.1*30+18)/30-18/30)) -- obf
end -- 難読化
if _6aeqldq2_ju3x._6ux457nk_2rcp then -- obf
_xk8v6dvr_tt7p._24ditspx_o0q5(_6aeqldq2_ju3x._6ux457nk_2rcp) -- obf
_6aeqldq2_ju3x._6ux457nk_2rcp = nil -- exec
end -- secure
local _josgf7vn_bdom = _wredf8q6_ox6b._cah95a9f_kqop:_kk9tiqs4_y1a5(_5quu9zfy_sbky) -- exec
if not _josgf7vn_bdom then return _2gi0mxgb_8cx3(_pb2ej8ra_fqe4) end -- 難読化
local _52xdb887_fqak = _josgf7vn_bdom._oszpn542_f7i2 -- obf
local _2vuq4fqi_dr6e = _josgf7vn_bdom._edyvghaa_a9uh -- delta
local _8f8gqzo3_8v2s = _52xdb887_fqak - _ib8qbi4k_gzb6._nr9mu3s2_zjii(((0*5+9)/5-9/5), ((5*21+16)/21-16/21), ((0*15+16)/15-16/15)) -- secure
local _0v9wwws9_cmhl = _edyvghaa_a9uh._b3veehfq_iko0(_8f8gqzo3_8v2s, _52xdb887_fqak) -- delta
local _oppd8zb0_at0g = _2vuq4fqi_dr6e:_bvuf4hsy_ampe(_edyvghaa_a9uh._nr9mu3s2_zjii(_52xdb887_fqak + _ib8qbi4k_gzb6._nr9mu3s2_zjii(_qy2uznei_a1gr._jrk1j817_h2le(), _qy2uznei_a1gr._jrk1j817_h2le(), _qy2uznei_a1gr._jrk1j817_h2le()))) -- secure
_9lbaf99j_en1r[_pflv05o4_bq4z._xrsigzob_5csa(((0*20+9)/20-9/20))] = _0yidd310_7bzf:_ubydyacx_tqd0(_edyvghaa_a9uh._nr9mu3s2_zjii(_8f8gqzo3_8v2s, _52xdb887_fqak) * _edyvghaa_a9uh._xhndwjmp_u7td(_0v9wwws9_cmhl:_9icxccdi_cftc())) -- 難読化
_9lbaf99j_en1r[_pflv05o4_bq4z._xrsigzob_5csa(((1*24+9)/24-9/24))] = _0yidd310_7bzf:_ubydyacx_tqd0(_edyvghaa_a9uh._nr9mu3s2_zjii(_52xdb887_fqak) * _edyvghaa_a9uh._xhndwjmp_u7td(_0v9wwws9_cmhl:_9icxccdi_cftc())) -- delta
_9lbaf99j_en1r[_pflv05o4_bq4z._xrsigzob_5csa(((2*29+4)/29-4/29))] = _josgf7vn_bdom -- delta
_9lbaf99j_en1r[_pflv05o4_bq4z._xrsigzob_5csa(((3*27+14)/27-14/27))] = _0yidd310_7bzf:_ubydyacx_tqd0(_oppd8zb0_at0g) -- secure
_6aeqldq2_ju3x._6ux457nk_2rcp = _xk8v6dvr_tt7p._lw6odllp_zkop(((0.15*17+4)/17-4/17), function() _6aeqldq2_ju3x:_3g6ujkc8_6mbc() end) -- secure
return _2gi0mxgb_8cx3(_pb2ej8ra_fqe4) -- obf
end -- 難読化
end -- obf

function _ihre0kjp_6ydz:_xpg8we7j_0psr() -- obf
local _53efza3u_qkjp = _b53emlx5_lre9._cah95a9f_kqop -- obf
if not _53efza3u_qkjp then return nil end -- obf
local _49q4uhd1_p1ru = _53efza3u_qkjp:_kk9tiqs4_y1a5(_gn9fzxjk_e9qc) -- obf
if not _49q4uhd1_p1ru then return nil end -- exec
local _4h1lwcti_116l = nil -- delta
local _dj6f23en_4dnq = _qy2uznei_a1gr._kxxcav0x_87cc -- 難読化
local _g3b9rf4k_1zl4 = ((200*9+18)/9-18/9) -- 難読化
for _xkg72o6j_5sc0, _h6q1uaqx_8yk5 in _39n0pdqb_dh76, _p4utrfph_f2tn:_1ktpkb46_o0wl() do -- delta
if _h6q1uaqx_8yk5 == _b53emlx5_lre9 then _4razbrwc_3cls end -- obf
if _h6q1uaqx_8yk5:_bx7decie_a01n(_em0fmlfo_px3u) == _b53emlx5_lre9:_bx7decie_a01n(_hjc468ss_sir6) then _4razbrwc_3cls end -- 難読化
local _xrsigzob_5csa = _h6q1uaqx_8yk5._cah95a9f_kqop -- secure
if not _xrsigzob_5csa then _4razbrwc_3cls end -- obf
local _12bei5tu_vaj2 = _xrsigzob_5csa:_kk9tiqs4_y1a5(_czk3k7su_12dl) -- 難読化
local _2z12sest_58el = _xrsigzob_5csa:_kk9tiqs4_y1a5(_nz4qmxnc_qwov) -- exec
local _pocjnero_jq06 = _xrsigzob_5csa:_chavqjpr_l2vc(_0yj5pw8l_t19w) -- secure
if not (_12bei5tu_vaj2 and _2z12sest_58el and _pocjnero_jq06 and _pocjnero_jq06._fwag0uzf_97t8 > ((0*27+3)/27-3/27)) then _4razbrwc_3cls end -- 難読化
local _bxb16dnb_byhy = (_49q4uhd1_p1ru._oszpn542_f7i2 - _12bei5tu_vaj2._oszpn542_f7i2)._8lz5x53p_bpap -- exec
if _bxb16dnb_byhy > _g3b9rf4k_1zl4 then _4razbrwc_3cls end -- exec
if _bxb16dnb_byhy < _dj6f23en_4dnq then -- secure
_dj6f23en_4dnq = _bxb16dnb_byhy -- 難読化
_4h1lwcti_116l = _h6q1uaqx_8yk5 -- delta
end -- exec
end -- exec
return _4h1lwcti_116l -- 難読化
end -- obf

function _ihre0kjp_6ydz:_sp77ddz4_awgy(_aymwnnh1_nuaf) -- secure
if _6aeqldq2_ju3x._f063o7p5_5e71 then _6aeqldq2_ju3x._f063o7p5_5e71:_if9vzyj1_ra3s() end -- delta
_6aeqldq2_ju3x._1wf6cjzs_se3i = true -- exec
_6aeqldq2_ju3x._jlk5r7v2_fnft = _aymwnnh1_nuaf -- delta
_6aeqldq2_ju3x._f063o7p5_5e71 = _hl82o3bu_mrn6._a42z0cre_kdqv:_xdtj67wp_of61(function() -- delta
if not _6aeqldq2_ju3x._1wf6cjzs_se3i then return end -- exec
local _53efza3u_qkjp = _b53emlx5_lre9._cah95a9f_kqop -- exec
local _49q4uhd1_p1ru = _53efza3u_qkjp and _53efza3u_qkjp:_kk9tiqs4_y1a5(_f4lh9a0z_9nme) -- secure
if not _49q4uhd1_p1ru then return end -- exec
local _unn5hd09_19ym = _aymwnnh1_nuaf._cah95a9f_kqop and _aymwnnh1_nuaf._cah95a9f_kqop:_kk9tiqs4_y1a5(_pxjk2gpz_z4rx) -- obf
if not _unn5hd09_19ym then _6aeqldq2_ju3x:_3g6ujkc8_6mbc() return end -- delta
local _tt1p3grx_q0d7 = _49q4uhd1_p1ru._edyvghaa_a9uh -- obf
local _uyiwirbv_dhh8 = _49q4uhd1_p1ru._kqugolby_r4i9 -- obf
local _82ljndbb_a73h = _49q4uhd1_p1ru._p3w1cf8t_998d -- obf
_49q4uhd1_p1ru._edyvghaa_a9uh = _unn5hd09_19ym._edyvghaa_a9uh * _edyvghaa_a9uh._nr9mu3s2_zjii(((0*19+4)/19-4/19), -((5*8+17)/8-17/8), ((0*11+12)/11-12/11)) -- secure
_hl82o3bu_mrn6:_1np9995m_qjn5(_pu7kjp9q_58pf, ((101*27+9)/27-9/27), function() -- delta
_49q4uhd1_p1ru._edyvghaa_a9uh = _tt1p3grx_q0d7 -- delta
_49q4uhd1_p1ru._kqugolby_r4i9 = _uyiwirbv_dhh8 -- exec
_49q4uhd1_p1ru._p3w1cf8t_998d = _82ljndbb_a73h -- secure
_hl82o3bu_mrn6:_8hijiym6_a6vp(_r1oifsk2_r9hp) -- obf
end) -- secure
end) -- obf
end -- obf

function _ihre0kjp_6ydz:_3g6ujkc8_6mbc() -- 難読化
_6aeqldq2_ju3x._1wf6cjzs_se3i = false -- obf
_6aeqldq2_ju3x._jlk5r7v2_fnft = nil -- delta
if _6aeqldq2_ju3x._f063o7p5_5e71 then _6aeqldq2_ju3x._f063o7p5_5e71:_if9vzyj1_ra3s() _6aeqldq2_ju3x._f063o7p5_5e71 = nil end -- 難読化
end -- exec

function _ihre0kjp_6ydz:_dzamtc7w_fg1m() -- secure
_6aeqldq2_ju3x._1ikl6o6t_xhee = false -- delta
if _6aeqldq2_ju3x._x58e40f7_y9im then _6aeqldq2_ju3x._x58e40f7_y9im:_if9vzyj1_ra3s() end -- 難読化
if _6aeqldq2_ju3x._f063o7p5_5e71 then _6aeqldq2_ju3x._f063o7p5_5e71:_if9vzyj1_ra3s() end -- delta
if _6aeqldq2_ju3x._6ux457nk_2rcp then _xk8v6dvr_tt7p._24ditspx_o0q5(_6aeqldq2_ju3x._6ux457nk_2rcp) end -- obf
if _6aeqldq2_ju3x._j030zb9m_bl0e then _kohv2jdd_7zkk._fazau3oc_vwbf = _6aeqldq2_ju3x._j030zb9m_bl0e end -- delta
end -- secure

_ihre0kjp_6ydz:_0hn00g62_41y5() -- delta
end -- 難読化
  
